grafana:
  image: grafana/grafana:latest
  ports:
    - "3000:3000"
  volumes:
    - ./:/var/lib/grafana/plugins/influxdb-flux-datasource
    - ./provisioning:/etc/grafana/provisioning
  environment:
    - TERM=linux
